### ISSUE TITLE
Investigate using Lerna for managing multi packages

### ISSUE THREAD

**Issue by whawker** [whawker/react-jsx-highcharts#112]
Currently this is all done by hand, but perhaps [Lerna](https://lernajs.io/) is a more appropriate and maintainable solution.

Dependency tree

```
└─ react-jsx-highstock-datepickers
  └─ react-jsx-highstock
    └─ react-jsx-highcharts
      └─ is-immutable (currently in separate repo, perhaps could be added here?)
```

cc @anajavi Any experience with this?

**Comment by anajavi** [comment]
Never used lerna. No idea how it works.

is-immutable is perhaps not needed when/if immutable-js 4 is released. Immutable 4 is tree shakable, so that function could be used straight from there.

**Comment by whawker** [comment]
Ah interesting, I wasn't aware of that, thanks!

As an aside, have you advice for improving the library? Improving documentation, more helper components like the datepickers?

**Comment by anajavi** [comment]
I think that this library is really nice abstraction around highcharts. More helpers would just make it harder to maintain.

Stable library with just enough features and timely updates when needed is actually the nicest thing:)

One thing that would make it more usable would be the flow typings. As they are visible in IDE, not much documentation would be needed besides them. I can setup the boilerplate, if you like?

**Comment by whawker** [comment]
That sounds great, I haven't done much with much Flow typing so would be interested to see how it works.

I've created #113 to track that separately.

**Comment by anajavi** [comment]
One small thing about the documentation. I think that the readme.md should start with:
- Introduction
- Installation
- Getting Started

At least those are things I usually read first for every library.

**Comment by anajavi** [comment]
I noticed that you have to ask in every issue sent by the users about the versions installed. Issue template would help here.

The template could be:
- Bug or Feature
- Description
- How to reproduce
- Versions
  - Library version
  - Highcharts version
  - React version

When users are filling up the version information, they usually end up testing with the newer version too.

**Comment by whawker** [comment]
Good idea, I'll knock that up now.

**Comment by anajavi** [comment]
I've been lately reading about lerna concepts. 

Questions:
**A) Is your current release workflow this:**
1. build react-jsx-highcharts
2. release react-jsx-highcharts
3. wait for it to appear in npm
4. update react-jsx-highstock package.json to depend on new version of react-jsx-highcharts
5. build react-jsx-highstock
6. release react-jsx-highstock
7. update react-jsx-highmaps package.json to depend on new version of react-jsx-highcharts
8. build react-jsx-highmaps
9. release react-jsx-higmaps

I am asking for the correct order because I think lerna can't handle waiting for appearance in npm(?).

It can be fixed  for UMD build with using [resolve.alias](https://webpack.js.org/configuration/resolve/#resolve-alias) in webpack.config.
The ESM build should be fine as is.

**B) Did you find any other problems when you tried lerna in a branch?**
