### ISSUE TITLE
Support for applying Highcharts theme

### ISSUE THREAD

**Issue by jvskriubakken** [whawker/react-jsx-highcharts#127]
#### Bug or Feature Request?

Feature Request

#### Description

Hi, thanks for making this great adapter for Highcharts. Is there a preferred way to apply a bundled Highcharts theme with react-jsx-highcharts?

#### Versions
* React JSX Highcharts version: 3.1.0
* Highcharts version: 6.1.0
* React version: 16.4.1

**Comment by whawker** [comment]
There is no special technique for adding a theme in React JSX Highcharts.

I would personally recommend using the [Style by CSS](https://whawker.github.io/react-jsx-highcharts/examples/StyleByCSS/index.html) import instead, rather than `Highcharts.theme`. They make the React components much less verbose... but if you'd rather use a theme.

```jsx
import Highcharts form 'highcharts'
import { withHighcharts, HighchartsChart, /* etc */ } from 'react-jsx-highcharts'

Highcharts.theme = {
  // theme settings here
}
Highcharts.setOptions(Highcharts.theme)

const MyChart = () => (
  <HighchartsChart>
    // Components here
  </HighchartsChart>
)

export default withHighcharts(MyChart, Highcharts)
```
