### ISSUE TITLE
Market Depth Example

### ISSUE THREAD

**Issue by arpitprod** [whawker/react-jsx-highcharts#148]
#### Feature Request?

Market Depth Example

#### Description

I saw a Market Depth example in highcharts github link
[https://github.com/highcharts/highcharts/issues/8564#issuecomment-402061246](url)
This is example code
[https://jsfiddle.net/daniel_s/tc7dswjd/](url)

and I tried to convert this example in react. This is my code link
[https://stackblitz.com/edit/base-chart-example-eezqwa?file=MyChart.js](url)

But this code is not working.

#### Versions
* React JSX Highcharts version: 3.1.0
* Highcharts version: 6.1.1
* React version: 16.3.2

**Comment by whawker** [comment]
Hi @arpitprod, there are a few issues here,

Firstly, in most cases React JSX Highcharts requires that `Series` are a child of an Axis

i.e. 
```jsx
<YAxis>
  <Series />
  <Series />
</YAxis>
```
not

```jsx
<YAxis />
<Series />
<Series />
```

Secondly your `fetch` implementation is incorrect - jQuery's `$.getJSON` and `fetch` do not have the same API, `$.getJSON` accepts a callback as the second parameter, whereas `fetch` is a function that returns a Promise, so it should be

```js
fetch('http://some.api/endpoint')
  .then(res => {
    if (res.ok) return res.json() // Parse the response as JSON
    // Else raise some error
  })
  .then(data => { // Data is the parsed JSON
    // Do something with data
  })
```
not
```js
fetch('http://some.api/endpoint', function (data) { /* This doesn't work */ })
```

I have updated your example so it works here: https://stackblitz.com/edit/base-chart-example-um6pkz?file=MyChart.js

P.s.
In your case, it would be better to use `AreaSeries` rather than `Series`

P.p.s.
In React JSX Highcharts everything is disabled unless you render the component, so `<Legend enabled={false} /> is meaningless, it would be easier to not render a Legend at all.
