### ISSUE TITLE
Allow "time" options to be specified

### ISSUE THREAD

**Issue by jacobweber** [whawker/react-jsx-highcharts#153]
#### Bug or Feature Request?
Feature request

#### Description
Allow the [time options](https://api.highcharts.com/highcharts/time) to be specified.

#### How to reproduce
N/A

#### Live demo demonstrating bug
N/A

#### Versions
* React JSX Highcharts version: 3.1.0
* Highcharts version: 6.0.7
* React version: 16.5

**Comment by whawker** [comment]
Hi @jacobweber, you can supply a timezone by passing a `time` prop to your `HighchartsChart` component

Example: https://stackblitz.com/edit/base-chart-example-73axnx?file=MyChart.js

It's worth noting though, Highcharts requires you to expose `moment` on the [global window object](https://github.com/highcharts/highcharts/blob/v6.1.2/js/parts/Time.js#L426) for timezone features to work 😞, which is why it might seem like this feature doesn't work.
