### ISSUE TITLE
Trouble rendering custom component with provideAxis

### ISSUE THREAD

**Issue by tlambert03** [whawker/react-jsx-highcharts#211]
#### Bug or Feature Request?
bug? (or probably me just doing something wrong)

#### Description
I'm trying to mimic your [custom component](https://whawker.github.io/react-jsx-highcharts/examples/CustomComponent/index.html) example, just swapping the datepicker for simple inputs, but I cannot seem to get  my custom component to render.  Console.log statements in the constructor and render methods never fire, and I cannot see the component in the DOM or in the react dev tools (though I _do_ see the Axis.Provider in the devtools).  Any tips would be greatly appreciated.

#### How to reproduce
have a look at the codesandbox below.  The missing component is called "XRangePickers"

#### Live demo demonstrating bug
https://codesandbox.io/s/confident-elgamal-xy3u8

#### Versions
* React JSX Highcharts version: 3.5.0
* Highcharts version: 7.1.1
* React version: 16.8.6

thanks a lot for this great package!

**Comment by tlambert03** [comment]
(for what it's worth, I'm grabbing `provideAxis from` `react-jsx-highcharts `instead of highstock)

**Comment by whawker** [comment]
Hi @tlambert03, apologies this could have been clearer in the documentation 🤦‍♂ 

The custom component example uses the `react-jsx-high`**stock** package rather than `react-jsx-highcharts`

* `react-jsx-highstock` makes the [XAxis default to having an `id` of `xAxis`](https://github.com/whawker/react-jsx-highcharts/blob/master/packages/react-jsx-highcharts/src/components/XAxis/XAxis.js#L18) to make it easier to worth with RangeSelector etc
* `react-jsx-highcharts` however, defaults to a UUID `id` - which is why your code doesn't work.

To fix your code, you simply need to override the default UUID, **by providing a known `id` to your `XAxis` component** (add make sure it matches the `axisId` you pass to your custom component).

```jsx
<XAxis id="xAxis">
  <XAxis.Title>xAxis</XAxis.Title>
</XAxis>

<XRangePickers axisId="xAxis" />
```

P.s. the `xAxis` string passed as the `id` prop here could be any value, it just needs to be the same as the value passed to `axisId`

**Comment by tlambert03** [comment]
aha!  Thanks.  makes sense... I admit I did wonder about the special significance of the id "xAxis"... but I failed to notice the special case for highstock.   I added a small comment to the codesandbox should anyone stumble on this in the future.

Thanks for your help, and thanks a lot for all your work.
