### ISSUE TITLE
Unable to switch from gauge to other chart types

### ISSUE THREAD

**Issue by louis269279** [whawker/react-jsx-highcharts#295]
#### Bug or Feature Request?
Bug, possibly due to misconfiguration (i.e. maybe I'm not rendering these charts properly?)

#### Description
I've set up this example where I try to allow the user to switch between chart types, but when I render a pie series and gauge series alternatively, it seems to crash and have this error: "Cannot read property 'acrossPanes' of undefined".

I'm not sure if I missed something, or this is just a bug.

#### How to reproduce
See demo.
It happens both ways (pie chart renders first then gauge, or gauge first then attempt to switch). You can modify the initial state in index.js to see other chart types rendered first, then gauge.

#### Live demo demonstrating bug
https://stackblitz.com/edit/stockchart-updatepoints-false-pwvint

#### Versions
* React JSX Highcharts version: Latest
* Highcharts version: Latest
* React version: Latest

**Comment by whawker** [comment]
I need to do more digging, but I suspect this is because gauge options are set on "init", and when the chart is changed in this way, the chart is not reinitialised.

I think when changing from pie to gauge, the chart was never set with the [`angular`](https://github.com/whawker/react-jsx-highcharts/blob/master/packages/react-jsx-highcharts/src/components/BaseChart/BaseChart.js#L122) flag.
Not sure on the problem when switching from gauge to pie, but I suspect it might be best to render 2 different charts in this use case.
