### ISSUE TITLE
Ideological questions about approach to architecture

### ISSUE THREAD

**Issue by elisechant** [whawker/react-jsx-highcharts#3]
Hey Will. 

Great idea with this repo and good job getting it out there on npm 👍 ! Legend!

I think that the way you've "reengineered' Highcharts declaratively is clever. I can see that you're building a lightweight chart instance and then adding the nested components (titles, axis, even series) as you move down the DOM tree. 

I'm wondering if you had other attempts or thinking to solve this? 

A problem (there are a few) with Highcharts is of course that it holds bidirectional state, so the state can get dirty easily. The other thing that has annoyed the shit out of me is the context of scope in events.

I was playing with an ideological idea (which you've inspired me to spike out now! :shipit:) of using the declarative DOM instead to effectively map the JSON config. This way, you could supply Highcharts constructor once with a state shape that it needs to render. Subsequent renders would destroy and then create new instance. 

I have been wrapping Highcharts with React and writing code like this (which is "reasonable" but feels wrong, but feels better than the giant JSON blob):

```
<BubbleChart title="Projects by status - Delivery"
                               series={[
                                {x:32.3,y:23.3},
                                {x:8.3,y:79.2},
                                {x:33.3,y:87.3},
                               ]}
                               xAxis={{title:{text:'Percentage completed (%)'}}}
                               yAxis={{title:{text:'Percentage spent (%)'}}} />
```

It's effectively a 1:1 mapping to the JSON blob. Sigh.

But it could easily look like this and be more Reacty: 

```
<BubbleChart>
            <Title text="Projects by status - Delivery" />
            <Series data={[
              {x:32.3,y:23.3},
              {x:8.3,y:79.2},
              {x:33.3,y:87.3},
            ]} />
            <Yaxis title={{text:'Percentage completed (%)'}} />
            <Xaxis title={{text:'Percentage spent (%)'}} />
          </BubbleChart>
```
          
Just wondering about ideological questions around how you came to your solution and what was some of your thinking?

**Comment by whawker** [comment]
@elisechant My idea is rather simplistic - as you've already noticed, I just create a Highcharts chart with everything disabled, and perform a `chart.update` with new config, when a sub component mounts/unmounts or its props change.

There is a bit of magic going on via React context: rather than passing the whole chart object around and risk React render thrashing, I use higher order components ([Chart](https://github.com/whawker/react-jsx-highcharts/blob/master/src/components/ChartProvider/index.js), [Axis](https://github.com/whawker/react-jsx-highcharts/blob/master/src/components/AxisProvider/index.js) and [Series](https://github.com/whawker/react-jsx-highcharts/blob/master/src/components/SeriesProvider/index.js)) as providers to obtain the chart from context, and inject Highcharts functions to the components. These injected functions have their scope bound to the correct Highcharts objects, which also means they shouldn't cause the wrapped component to re-render.

I do have some slight concerns that some of the internal state of Highcharts isn't reflected in the React components. For instance when hiding a series via clicking on a Legend item, the React component for that series doesn't know that it has been hidden.

I did consider trying to using Redux, and treating Highcharts' internal state as a store, but I don't think the structure of this state lends itself very well to that. Although I never wrote any code to spike out that idea, so it could be an area to explore.

My main goal is to try and hide the complexity of Highcharts, and make things feel more familiar to a React developer. I wanted to avoid passing around JSON configuration objects where possible, as that (I felt) detracts from the idea of abstracting that complexity away.

I'm more that open to suggestions though, this was originally intended as a proof of concept, so it's very much a work in progress! 😄

**Comment by whawker** [comment]
Unrelated, but also something I want to explore is being able to use ImmutableJS List objects as data for series.

**Comment by elisechant** [comment]
Thanks Will.

Oh yeah of course `context`! Gotcha. Good save on the thrashing! A clever idea. I really like this approach.

I had also considered the Redux thing to keep track of state, but still don't know that that would really solve the initial rendering and concerned about "rehydrating" Highcharts because of its monolithicness and internal state setting.

Another painpoint i've found is having to manage json configuration updates across its' state objects  to enable features for a "type of chart", ie, a percentage bubble chart needs series data with min and max (0 - 100) attributes, chart attributes, various yAxis and xAxis attributes as well. I find that i'm writing middleware to apply all changes to the json in one hit. This probably has nothing to do with you repo, but just putting it out there, lots to think about and lots to do here. 

I'll look forward to watching react-jsx-highcharts evolve 👍
