### ISSUE TITLE
onSetExtremes prop is not updated

### ISSUE THREAD

**Issue by hukka** [whawker/react-jsx-highcharts#308]
#### Bug or Feature Request?
Bug.

#### Description
Trying to update the onSetExtremes event handler (for closures) will not work, but the initial value is always used. This can be surprising when trying to close over the previous extremes in the event handler (for example to check if new data needs to be loaded). It can be worked around with refs, but this should be documented.

#### Live demo demonstrating bug
https://stackblitz.com/edit/base-chart-example-closure-in-event-handler?file=MyChart.js
open the console, change extremes using the range selectors. Notice how the logged value in the chart's render function keeps changing, but the closed value logged from the event handler is always the same (the first one), even though a new event handler is created on every render.

**Comment by hukka** [comment]
Perhaps a matter of using `.update` vs `.addEvent`, as mentioned in https://github.com/highcharts/highcharts/issues/6538 ?

**Comment by anajavi** [comment]
The axis events are bound only on createAxis:
https://github.com/whawker/react-jsx-highcharts/blob/c3d3106d42195415e6afa6475ed9ad8821feae97/packages/react-jsx-highcharts/src/components/Axis/Axis.js#L65

This is probably a bug or missing functionality. @whawker is there are reason why the axis eventhandlers are not updated when prop changes?

As there are more problems with highcharts event handlers (for example: https://github.com/highcharts/highcharts/issues/12067), I have been thinking about proxying all the eventhandlers so that they don't need to be passed to highcharts at all.

Something like this:
```js
useCallback((eventName, ...args) => {
  props.[`on${eventName}`](...args);
},[]);
```

It is however a little tricky as some of those events need to pass ```this``` bound to something for example [legendItemClick](https://api.highcharts.com/class-reference/Highcharts#.SeriesLegendItemClickCallbackFunction)

**Comment by whawker** [comment]
> @whawker is there are reason why the axis eventhandlers are not updated when prop changes?

I never really envisioned the event handlers changing, which is an obvious oversight now 🤦‍♂️ 

If we we're to implement something similar to `useModifiedProps` for event handlers, we would need to have documentation on function equality between renders (i.e. wrapping in the event handler in `useCallback`) otherwise we might end up adding the same event handler multiple times?

Going completely off topic, I've been wondering if `useModifiedProps` is a mistake, currently when props change we figure out which ones have changed, and commit them as updates to the wrapped Highcharts chart. 

I wonder instead if we should be utilising the `oneToOne` option of [`chart.update`](https://api.highcharts.com/class-reference/Highcharts.Chart#update) so that we can sure that the state in React representation of the chart, is the same as the internal Highcharts representation. However this might be undermining one of the fundamental principles of this project in the first place, to avoid destroying the chart completely between React re-renders)

**Comment by anajavi** [comment]
> I never really envisioned the event handlers changing, which is an obvious oversight now 🤦‍♂️

Before hooks the eventhandlers were class methods, so they wouldn't change. 

> If we we're to implement something similar to `useModifiedProps` for event handlers, we would need to have documentation on function equality between renders (i.e. wrapping in the event handler in `useCallback`) otherwise we might end up adding the same event handler multiple times?

Would [useManualEventHandlers](https://github.com/whawker/react-jsx-highcharts/blob/master/packages/react-jsx-highcharts/src/components/UseManualEventHandlers/index.js) work here?

**Comment by whawker** [comment]
> Before hooks the eventhandlers were class methods, so they wouldn't change.

Cool. After hooks, do you think we should be advising `useCallback`? Or some other strategy?

> Would `useManualEventHandlers` work here?

Possibly? I need to read the Highcharts source to see what happens to manually added events on update (as some things get destroyed), need to check if manually added events are reassigned to the newly created object.

**Comment by hukka** [comment]
While event handlers are often class methods, it's not uncommon to see code where the handler is created as a lambda too, in style of:
```
<MyComponent handler={() => props.parentHandler(state.myChangingState)} />
```
so I could imagine that even code still using class based components might get tripped by this.

> After hooks, do you think we should be advising useCallback? Or some other strategy?

It might be good form to use useCallback in the examples, but unless there's a worse impact than usual, I would leave it as implicit React hooks knowledge. The same thing applies to any other case of passing functions as props. Or any non primitive data that is not wrapped in useMemo, for that matter.

**Comment by anajavi** [comment]
It seems that this problem could now be fixed quite easily as highcharts has fixed a bug related to it:
https://github.com/highcharts/highcharts/pull/15658
