### ISSUE TITLE
Strange behavior when RangeSelector and Navigator is used together

### ISSUE THREAD

**Issue by veloek** [whawker/react-jsx-highcharts#339]
#### Bug or Feature Request?
Bug

#### Description
Something weird happens when you have a stock chart with both RangeSelector and Navigator. When the component is unmounted, it is moved/added directly under document.body. This happens on every unmount, creating multiple copies of the same element.

I've tested different versions of Highcharts and it seems like it was introduced with Highcharts 9.0.0 because I can't reproduce it in version 8.2.2. 

#### How to reproduce
I've made a sandboxed example that demonstrates the behavior with a comparison between native Highcharts and RJH.

#### Live demo demonstrating bug
https://codesandbox.io/s/react-highcharts-comparison-13eix

#### Versions
* React JSX Highcharts version: 4.2.1
* Highcharts version: 9.1.2
* React version: 17.0.2

**Comment by anajavi** [comment]
Funnily #332 seems to fix this.

I suppose this has to do with the timing of highstock chart destroy. In master version the chart is destroyed after the div-element has already removed from DOM. I guess  #332 changes the timing so that the div-element is destroyed after the chart.

@veloek can you confirm that #332 fixes this for you too?

The fixing code is in react-jsx-highcharts package instead of highstock. It can be tested quickly by:
```sh
cd react-jsx-highcharts/packages/react-jsx-highcharts
npm run build:prod && cp -r dist/* <yourproject>/node_modules/react-jsx-highcharts/dist/
```

**Comment by veloek** [comment]
@anajavi Yeah, this seems to do the trick! 👍
