### ISSUE TITLE
How does this library compare to https://github.com/kirjs/react-highcharts?

### ISSUE THREAD

**Issue by adamalawrence** [whawker/react-jsx-highcharts#51]
I'm deciding which one to use. The react-highcharts is obviously more popular, but I'm wondering, @whawker, if you'd describe some reasons to use react-jsx-highcharts over the other? Thank you!

**Comment by nslocum** [comment]
`react-jsx-highcharts` provides a declarative interface to the highcharts library.

React is declarative in nature and unfortunately, `react-highcharts` doesn't provide a declarative interface to the Highcharts library. It's really just a dumb wrapper that gives you easy access to their raw charting API. It does very little beyond that and doesn't adhere to how React apps are built. Because of this, it's **very** difficult to integrate dynamic charts into React using `react-highcharts`. You'll really feel the pain when you need to update chart data, change display settings, tie into the range selector, etc.

Here's a great overview of declarative programming with React and why it's important:
https://codeburst.io/declarative-vs-imperative-programming-a8a7c93d9ad2

**Comment by whawker** [comment]
Thanks @nslocum! 

As Nick mentioned, the main motivation for this library was to enable dynamic charts, by making Highcharts charts behave like a React developer would expect.

Breaking the chart down into separate components means that we can intelligently update the Highcharts object behind the scenes depending on which React props changed. Rather than passing a large config object as a single property.

I go into more detail on this [blog post](https://www.highcharts.com/blog/post/highcharts-abstraction-react-components-react-jsx-highcharts/), but I'll be happy to answer any more question if you have them.

**Comment by adamalawrence** [comment]
Thanks for the overview! You clearly put a lot of thought into your design.
