### ISSUE TITLE
React-JSX-Highstock example with date range picker does not work

### ISSUE THREAD

**Issue by creativeleep** [whawker/react-jsx-highcharts#73]
After a week of debugging, it appears that something in the way React handles dot notation appears to have been broken. 

In the example and ALL other references to react-jsx-highstock with date range pickers, the code uses...
`<DayPicker.Input />` 

This however does not work unless the import statement explicitly includes...
`import { DayPickerInput } from 'react-day-picker/lib/src/DayPickerInput;' ` but the repo example uses the following import `import DayPicker from 'react-day-picker;` instead.

So the problem is with the import statement only importing the main default class of DayPicker and the dot notation not being recognized. The solution is to load the correct import { DayPickerInput } and dropping the dot notation to be more explicit.
`<DayPickerInput />`

**Comment by whawker** [comment]
Ahh, good spot.

In the examples I am using React Day Picker from the [browser export](https://github.com/whawker/react-jsx-highcharts/blob/master/examples/webpack.config.js#L70), rather than from the NPM module. 
The browser global exports as `DayPicker.Input` but the NPM modules exports as DatePickerInput.

You can see how to use React DayPicker inputs [here](https://github.com/whawker/react-jsx-highcharts/blob/master/packages/react-jsx-highstock-datepickers/src/index.js) or alternatively you can use it as an [importable NPM module](https://www.npmjs.com/package/react-jsx-highstock-datepickers) - which is now fixed

Note to self, I need to fix these misleading examples (#75)
